# Generated by Django 4.2.10 on 2024-08-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_access_open', models.BooleanField(default=False)),
                ('write_access_open', models.BooleanField(default=False)),
                ('start_access_date', models.DateTimeField(null=True, verbose_name='Дата и время начала доступа')),
                ('end_access_date', models.DateTimeField(null=True, verbose_name='Дата и время окончания доступа')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('last_update_date', models.DateField(auto_now=True, db_column='last_update_date')),
            ],
        ),
        migrations.CreateModel(
            name='AccessReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала курса')),
                ('course_access', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date', null=True)),
                ('last_update_date', models.DateField(auto_now=True, db_column='last_update_date', null=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('link', models.URLField(max_length=250, verbose_name='Ссылка')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date', null=True)),
                ('last_update_date', models.DateField(auto_now=True, db_column='last_update_date', null=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('last_update_date', models.DateField(auto_now=True, db_column='last_update_date')),
            ],
        ),
        migrations.CreateModel(
            name='PricesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.group')),
            ],
        ),
    ]
